---
- name: Create database user and privileges.
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    name: "{{ item.db_user }}"
    password: "{{ item.db_passwd }}"
    priv: "{{ item.db_name }}.*:ALL"
    state: present
  loop: "{{ application_database_users }}"
  when: application_database_users is defined

- name: Create application databases when they exist
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    name: "{{ item.db_name }}"
    state: present
  loop: "{{ application_databases }}"
  when: application_databases is defined

# mysql_db module appears to have a bug when trying to decompress .gz files
# Currently using shell to read and pass sql file to mysql to impprt
# TODO Check back with mysql_db module for fix.
- name: Import application database schemas if they exist.
  shell: zcat "{{ item.db_archive }}" | mysql -uroot -p"{{ mysql_root_passwd }}" "{{ item.db_name }}"
  loop: "{{ application_databases }}"
  when: application_databases is defined