---
# Tasks to remove current mysql instance
- include_tasks: remove-mysql.yml

# Tasks to install MySQL and set a permanent root password
- include_tasks: mysql-install.yml

# Tasks to create users and databases when provided
- include_tasks: create-database.yml