---
- include_tasks: remove-mysql.yml
  when:
    - reinstall_mysql is defined
    - reinstall_mysql == True

- name: Check if mysql file in /etc/sysconfig exists
  stat:
    path: /etc/sysconfig/mysql
  register: mysql_sysconf

- include_tasks: mysql-install.yml
  when:
    - msyql_sysconf is not defined
    - mysql_sysconf.stat.exists == False

- include_tasks: create-database.yml
  when:
    - recreate_db is defined
    - recreate_db == True

